name: Add GitHub Release Tag

on:
    push:
        tags:
            - '@xchart/*' # Push events to matching @xchart/*, i.e. @xchart/core@0.0.1-alpha.1

# $GITHUB_REF_NAME - https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Get pkgName for tag
              id: tag
              run: |
                  # matching @xchart/vue@0.0.1-alpha.1 etc
                  # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
                  str=${GITHUB_REF_NAME#*/}
                  # `%@*` truncates @ and version number from the right side.
                  pkgName=${str%@*}
                  echo "::set-output name=pkgName::$pkgName"

            - name: Create Release for Tag
              id: release_tag
              uses: yyx990803/release-tag@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  body: |
                      Please refer to [CHANGELOG.md](https://github.com/xchartjs/xchart/blob/${{ github.ref_name }}/packages/${{ steps.tag.outputs.pkgName }}/CHANGELOG.md) for details.
